config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/dashboard', to: 'dashboard#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  def self.update_or_create(auth)
    user = find_by(uid: auth[:uid]) || User.new
    user.attributes = {
      uid: auth[:uid],
      provider: auth[:provider],
      nickname: auth[:info][:nickname],
      name: auth[:info][:name],
      email: auth[:info][:email],
      image: auth[:info][:image],
      token: auth[:credentials][:token]
    }
    user.save
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @user = current_user
    @basic_info = GithubService.new(@user).get_basic_info
    @starred_count = GithubService.new(@user).get_starred_repos_count
    @recent_commits = GithubService.new(@user).get_recent_commits
    @following_commits = GithubService.new(@user).get_recent_following_commits
    @repos = GithubService.new(@user).get_repos
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.update_or_create(request.env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/index.html.erb
<div class="container-fluid container-profile">

	<div class="row justify-content-md-center">

		<div class="col col-md-2">

			<div class="avatar">
				<%= image_tag(@user.image) %>	
			</div>
			<br>
			<h3><%= @user.name %></h3>
			<p><%= @user.nickname %></p>
			
		</div>

		

		<div class="col col-md-8">

			<div class="basic_info">
				<div class="starred_repos">
					Starred Repos (<%= @starred_count %>)
				</div>

				<div class="followers">
					Followers (<%= @basic_info[:followers] %>)
				</div>

				<div class="following">
					Following (<%= @basic_info[:following] %>)
				</div>	
			</div>

			<div class="commit_feed">
				Commits
				<ul class="commit_list">
					<% @recent_commits.each do |commit| %>
					<li class="commit">
						<p><%= commit[:commit][:message] %></p>
						<p><%= commit[:repository][:full_name] %></p>
						<p><%= commit[:commit][:author][:date] %></p>
					</li>
					<% end %>
				</ul>
			</div>

			<div class="following_commit_feed">
				Follower Activity
				<ul class="following_user_list">
					<% @following_commits.each do |user, commits| %>
					<li class="following_user">
						<h5><%= user %></h5>
						<ul class="following_user_commits">
							<% commits.each do |commit| %>
							<li class="following_commit">
									<p><%= commit[:commit][:message] %></p>
									<p><%= commit[:repository][:full_name] %></p>
									<p><%= commit[:commit][:author][:date] %></p>
							</li>
							<% end %>
						</ul>
					</li>
					<% end %>
				</ul>
			</div>

			<div class="repos">
				Repositories (<%= @repos.count %>)
				<ul class="repo_feed">
					<% @repos.each do |repo| %>
					<li class="repo">
						<h5><%= repo[:full_name] %></h5>
						<p><%= repo[:language] %></p>
						<p><%= repo[:updated_at] %></p>
					</li>
					<% end %>
				</ul>
			</div>
			
		</div>


		
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<% if session[:user_id] %>
  	<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #201e1e">
	  <a class="navbar-brand" href="/">Github Clone</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	    <form class="form-inline my-2 my-lg-0">
	      <input class="form-control mr-sm-2" type="text" placeholder="Search Github" aria-label="Search">
	    </form>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item">
	        <a class="nav-link" href="#">Pull Requests<span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Issues</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Marketplace</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="#">Explore</a>
	      </li>
	    </ul>
	    <ul class="navbar-nav">
		    <li class="nav-item dropdown">
	        	<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          +
	        	</a>
	        	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
		          <a class="dropdown-item" href="#">New Repository</a>
		          <a class="dropdown-item" href="#">Import Repository</a>
		          <a class="dropdown-item" href="#">New Gist</a>
		          <a class="dropdown-item" href="#">New Organization</a>
	        	</div>
	      	</li>
	    </ul>
	    <ul class="navbar-nav">
	      	<li class="nav-item dropdown">
	        	<a class="nav-link dropdown-toggle" href="" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	          <%= image_tag(current_user.image, class: 'profile-pic') %>
	        	</a>
	        	<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
	        	  <p class="dropdown-item">Signed in as <%= current_user.nickname %></p>
		          <a class="dropdown-item" href="#">Your Profile</a>
		          <a class="dropdown-item" href="#">Your stars</a>
		          <a class="dropdown-item" href="#">Your Gists</a>
		          <div class="dropdown-divider"></div>
		          <a class="dropdown-item" href="#">Help</a>
		          <a class="dropdown-item" href="#">Settings</a>
		          <a class="dropdown-item" href="/logout">Logout</a>
	        	</div>
	      	</li>
	    </ul>
	  </div>
	</nav>
	<% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="container-fluid container-login">
	<div class="jumbotron login-box">
		<%= link_to "Login with Github", github_login_path, class: "btn btn-secondary" %>
	</div>
</div>